import { Course, SubjectType } from './types';
import { ElementData } from './types';

export const ELEMENTS: ElementData[] = [
  {"symbol":"H","name":"Vodorod","category":"nometall","state":"gaz","oxid":[1,-1],"ion":"H⁺","reactivity":"yuqori","notes":"H₂ hosil qiladi; kislorod, galogenlar va metallar bilan reaksiyaga kirishadi; ba'zi hollarda kuchli qaytaruvchi."},
  {"symbol":"He","name":"Geliy","category":"asil gaz","state":"gaz","oxid":[],"ion":null,"reactivity":"yo'q","notes":"Inert; normal sharoitda barqaror birikmalar hosil qilmaydi."},
  {"symbol":"Li","name":"Litiy","category":"ishqoriy metall","state":"qattiq","oxid":[1],"ion":"Li⁺","reactivity":"yuqori","notes":"Suv bilan shiddatli reaksiyaga kirishadi; nometallar bilan ionli tuzlar hosil qiladi."},
  {"symbol":"Be","name":"Berilliy","category":"ishqoriy yer metall","state":"qattiq","oxid":[2],"ion":"Be²⁺","reactivity":"o'rta","notes":"Kovalent xususiyatli Be birikmalarini hosil qiladi; galogenlar bilan reaksiyaga kirishadi."},
  {"symbol":"B","name":"Bor","category":"metalloid","state":"qattiq","oxid":[3],"ion":null,"reactivity":"past","notes":"Kovalent birikmalar hosil qiladi; kuchli oksidlovchilar bilan reaksiyaga kirishadi."},
  {"symbol":"C","name":"Uglerod","category":"nometall","state":"qattiq","oxid":[-4,4],"ion":null,"reactivity":"o'rta","notes":"CO₂, CO hosil qiladi; organik kimyoda asosiy element."},
  {"symbol":"N","name":"Azot","category":"nometall","state":"gaz","oxid":[-3,1,2,3,4,5],"ion":null,"reactivity":"past","notes":"N₂ sifatida barqaror; yuqori energiyada H₂ bilan reaksiyaga kirishadi; nitridlar hosil qiladi."},
  {"symbol":"O","name":"Kislorod","category":"nometall","state":"gaz","oxid":[-2],"ion":null,"reactivity":"yuqori","notes":"Kuchli oksidlovchi; ko'plab elementlar bilan oksidlar hosil qiladi."},
  {"symbol":"F","name":"Ftor","category":"galogen","state":"gaz","oxid":[-1],"ion":"F⁻","reactivity":"juda yuqori","notes":"Eng faol galogen; deyarli hamma narsa bilan reaksiyaga kirishadi."},
  {"symbol":"Ne","name":"Neon","category":"asil gaz","state":"gaz","oxid":[],"ion":null,"reactivity":"yo'q","notes":"Inert; odatda birikmalar hosil qilmaydi."},
  {"symbol":"Na","name":"Natriy","category":"ishqoriy metall","state":"qattiq","oxid":[1],"ion":"Na⁺","reactivity":"yuqori","notes":"Suv bilan kuchli reaksiyaga kirishadi; ionli tuzlar hosil qiladi."},
  {"symbol":"Mg","name":"Magniy","category":"ishqoriy yer metall","state":"qattiq","oxid":[2],"ion":"Mg²⁺","reactivity":"o'rta","notes":"Kislotalar bilan reaksiyaga kirishadi; MgO va tuzlar hosil qiladi."},
  {"symbol":"Al","name":"Alyuminiy","category":"o'tishdan keyingi metall","state":"qattiq","oxid":[3],"ion":"Al³⁺","reactivity":"past","notes":"Himoya oksid qatlami hosil qiladi; kuchli asoslar bilan reaksiyaga kirishadi."},
  {"symbol":"Si","name":"Kremniy","category":"metalloid","state":"qattiq","oxid":[4,-4],"ion":null,"reactivity":"past","notes":"SiO₂ hosil qiladi; galogenlar bilan reaksiyaga kirishadi."},
  {"symbol":"P","name":"Fosfor","category":"nometall","state":"qattiq","oxid":[-3,3,5],"ion":null,"reactivity":"o'rta-yuqori","notes":"Kislorod bilan reaksiyaga kirishadi; fosfatlar hosil qiladi."},
  {"symbol":"S","name":"Oltingugurt","category":"nometall","state":"qattiq","oxid":[-2,4,6],"ion":"S²⁻","reactivity":"o'rta","notes":"Sulfidlar hosil qiladi; sulfatlargacha oksidlanadi."},
  {"symbol":"Cl","name":"Xlor","category":"galogen","state":"gaz","oxid":[-1,1,3,5,7],"ion":"Cl⁻","reactivity":"juda yuqori","notes":"Kuchli oksidlovchi; metallar va H₂ bilan reaksiyaga kirishadi."},
  {"symbol":"Ar","name":"Argon","category":"asil gaz","state":"gaz","oxid":[],"ion":null,"reactivity":"yo'q","notes":"Normal sharoitda butunlay inert."},
  {"symbol":"K","name":"Kaliy","category":"ishqoriy metall","state":"qattiq","oxid":[1],"ion":"K⁺","reactivity":"juda yuqori","notes":"Suv bilan shiddatli reaksiyaga kirishadi; tuzlar hosil qiladi."},
  {"symbol":"Ca","name":"Kaltsiy","category":"ishqoriy yer metall","state":"qattiq","oxid":[2],"ion":"Ca²⁺","reactivity":"yuqori","notes":"Suv bilan reaksiyaga kirishadi; CaO, CaCl₂ hosil qiladi."},
  {"symbol":"Sc","name":"Skandiy","category":"o'tish metalli","state":"qattiq","oxid":[3],"ion":"Sc³⁺","reactivity":"o'rta","notes":"Barqaror ionli birikmalar hosil qiladi."},
  {"symbol":"Ti","name":"Titan","category":"o'tish metalli","state":"qattiq","oxid":[4],"ion":"Ti⁴⁺","reactivity":"past","notes":"TiO₂ hosil qiladi; chidamli metall."},
  {"symbol":"V","name":"Vanadiy","category":"o'tish metalli","state":"qattiq","oxid":[2,3,4,5],"ion":null,"reactivity":"o'rta","notes":"Ko'plab oksidlar hosil qiladi."},
  {"symbol":"Cr","name":"Xrom","category":"o'tish metalli","state":"qattiq","oxid":[3,6],"ion":null,"reactivity":"o'rta","notes":"Cr₂O₃, xromatlar hosil qiladi."},
  {"symbol":"Mn","name":"Marganets","category":"o'tish metalli","state":"qattiq","oxid":[2,4,7],"ion":null,"reactivity":"o'rta-yuqori","notes":"MnO₂, permanganat hosil qiladi."},
  {"symbol":"Fe","name":"Temir","category":"o'tish metalli","state":"qattiq","oxid":[2,3],"ion":null,"reactivity":"o'rta","notes":"Oson oksidlanadi; kislotalar bilan reaksiyaga kirishadi."},
  {"symbol":"Co","name":"Kobalt","category":"o'tish metalli","state":"qattiq","oxid":[2,3],"ion":null,"reactivity":"o'rta","notes":"Kompleks ionlar hosil qiladi."},
  {"symbol":"Ni","name":"Nikel","category":"o'tish metalli","state":"qattiq","oxid":[2],"ion":null,"reactivity":"past","notes":"O'rtacha reaktivlik; barqaror."},
  {"symbol":"Cu","name":"Mis","category":"o'tish metalli","state":"qattiq","oxid":[1,2],"ion":"Cu²⁺","reactivity":"o'rta-past","notes":"CuO, Cu₂O, tuzlar hosil qiladi."},
  {"symbol":"Zn","name":"Rux","category":"o'tishsimon metall","state":"qattiq","oxid":[2],"ion":"Zn²⁺","reactivity":"o'rta","notes":"Kislotalar bilan reaksiyaga kirishadi; ZnO hosil qiladi."},
  {"symbol":"Ga","name":"Galliy","category":"o'tishdan keyingi metall","state":"qattiq","oxid":[3],"ion":"Ga³⁺","reactivity":"past","notes":"Oksidlar va galogenidlar hosil qiladi."},
  {"symbol":"Ge","name":"Germaniy","category":"metalloid","state":"qattiq","oxid":[4],"ion":null,"reactivity":"past","notes":"Kovalent birikmalar hosil qiladi."},
  {"symbol":"As","name":"Mishyak","category":"metalloid","state":"qattiq","oxid":[-3,3,5],"ion":null,"reactivity":"o'rtacha","notes":"Arsenidlar hosil qiladi; oksidlanadi."},
  {"symbol":"Se","name":"Selen","category":"nometall","state":"qattiq","oxid":[-2,4,6],"ion":null,"reactivity":"o'rtacha","notes":"Selenidlar, oksidlar hosil qiladi."},
  {"symbol":"Br","name":"Brom","category":"galogen","state":"suyuq","oxid":[-1,1,3,5],"ion":"Br⁻","reactivity":"yuqori","notes":"Kuchli oksidlovchi; keng ko'lamda reaksiyaga kirishadi."},
  {"symbol":"Kr","name":"Kripton","category":"asil gaz","state":"gaz","oxid":[],"ion":null,"reactivity":"juda past","notes":"Juda kamdan-kam hollarda ekstremal sharoitlarda birikmalar hosil qiladi."},
  {"symbol":"Rb","name":"Rubidiy","category":"ishqoriy metall","state":"qattiq","oxid":[1],"ion":"Rb⁺","reactivity":"juda yuqori","notes":"Suv bilan portlaydi."},
  {"symbol":"Sr","name":"Stronsiy","category":"ishqoriy yer metall","state":"qattiq","oxid":[2],"ion":"Sr²⁺","reactivity":"yuqori","notes":"Suv bilan reaksiyaga kirishadi; oson tuzlar hosil qiladi."},
  {"symbol":"Y","name":"Ittriy","category":"o'tish metalli","state":"qattiq","oxid":[3],"ion":"Y³⁺","reactivity":"o'rta","notes":"Oksidlar va galogenidlar hosil qiladi."},
  {"symbol":"Zr","name":"Tsirkoniy","category":"o'tish metalli","state":"qattiq","oxid":[4],"ion":"Zr⁴⁺","reactivity":"past","notes":"ZrO₂ hosil qiladi; barqaror."},
  {"symbol":"Nb","name":"Niobiy","category":"o'tish metalli","state":"qattiq","oxid":[5],"ion":null,"reactivity":"past","notes":"Oksidlar hosil qiladi; korroziyaga chidamli."},
  {"symbol":"Mo","name":"Molibden","category":"o'tish metalli","state":"qattiq","oxid":[4,6],"ion":null,"reactivity":"o'rta","notes":"MoO₃ hosil qiladi; katalizator."},
  {"symbol":"Tc","name":"Texneciy","category":"o'tish metalli","state":"qattiq","oxid":[4,7],"ion":null,"reactivity":"o'rta","notes":"Oksidlar hosil qiladi; radioaktiv."},
  {"symbol":"Ru","name":"Ruteniy","category":"o'tish metalli","state":"qattiq","oxid":[3,4,8],"ion":null,"reactivity":"o'rta-past","notes":"Oksidlar, komplekslar hosil qiladi."},
  {"symbol":"Rh","name":"Rodiy","category":"o'tish metalli","state":"qattiq","oxid":[3],"ion":null,"reactivity":"past","notes":"Barqaror, katalitik."},
  {"symbol":"Pd","name":"Palladiy","category":"o'tish metalli","state":"qattiq","oxid":[2,4],"ion":null,"reactivity":"past","notes":"Katalizator; vodorodni yutadi."},
  {"symbol":"Ag","name":"Kumush","category":"o'tish metalli","state":"qattiq","oxid":[1],"ion":"Ag⁺","reactivity":"past","notes":"AgCl cho'kmasini hosil qiladi; kislotalar bilan reaksiyasi past."},
  {"symbol":"Cd","name":"Kadmiy","category":"metall","state":"qattiq","oxid":[2],"ion":"Cd²⁺","reactivity":"o'rta","notes":"CdO, galogenidlar hosil qiladi."},
  {"symbol":"In","name":"Indiy","category":"o'tishdan keyingi metall","state":"qattiq","oxid":[3],"ion":"In³⁺","reactivity":"past","notes":"Yumshoq metall, galogenidlar hosil qiladi."},
  {"symbol":"Sn","name":"Qalay","category":"o'tishdan keyingi metall","state":"qattiq","oxid":[2,4],"ion":"Sn²⁺","reactivity":"o'rta-past","notes":"Qalay(II) va qalay(IV) birikmalarini hosil qiladi."},
  {"symbol":"Sb","name":"Surma","category":"metalloid","state":"qattiq","oxid":[3,5],"ion":null,"reactivity":"o'rta","notes":"Antimonidlar va oksidlar hosil qiladi."},
  {"symbol":"Te","name":"Tellur","category":"metalloid","state":"qattiq","oxid":[-2,4,6],"ion":null,"reactivity":"o'rta","notes":"Telluridlar hosil qiladi; oksidlanadi."},
  {"symbol":"I","name":"Yod","category":"galogen","state":"qattiq","oxid":[-1,1,3,5,7],"ion":"I⁻","reactivity":"o'rta-yuqori","notes":"Yodidlar hosil qiladi; o'rtacha reaktiv galogen."},
  {"symbol":"Xe","name":"Ksenon","category":"asil gaz","state":"gaz","oxid":[2,4,6,8],"ion":null,"reactivity":"juda past","notes":"Maxsus sharoitlarda ksenon ftoridlari hosil qiladi."},
  {"symbol":"Cs","name":"Tseziy","category":"ishqoriy metall","state":"qattiq","oxid":[1],"ion":"Cs⁺","reactivity":"juda yuqori","notes":"Suv bilan o'ta kuchli reaksiyaga kirishadi."},
  {"symbol":"Ba","name":"Bariy","category":"ishqoriy yer metall","state":"qattiq","oxid":[2],"ion":"Ba²⁺","reactivity":"yuqori","notes":"BaSO₄ cho'kmasini hosil qiladi."},
  {"symbol":"La","name":"Lantan","category":"lantanoid","state":"qattiq","oxid":[3],"ion":"La³⁺","reactivity":"o'rta","notes":"Oksidlar, galogenidlar hosil qiladi."},
  {"symbol":"Ce","name":"Seriy","category":"lantanoid","state":"qattiq","oxid":[3,4],"ion":"Ce³⁺","reactivity":"o'rta","notes":"CeO₂ hosil qiladi; oksidlanuvchan."},
  {"symbol":"Pr","name":"Prazeodim","category":"lantanoid","state":"qattiq","oxid":[3],"ion":"Pr³⁺","reactivity":"o'rta","notes":"Oksidlar hosil qiladi."},
  {"symbol":"Nd","name":"Neodim","category":"lantanoid","state":"qattiq","oxid":[3],"ion":"Nd³⁺","reactivity":"o'rta","notes":"Xloridlar, oksidlar hosil qiladi."},
  {"symbol":"Pm","name":"Prometiy","category":"lantanoid","state":"qattiq","oxid":[3],"ion":"Pm³⁺","reactivity":"o'rta","notes":"Radioaktiv."},
  {"symbol":"Sm","name":"Samariy","category":"lantanoid","state":"qattiq","oxid":[3],"ion":"Sm³⁺","reactivity":"o'rta","notes":"Oksidlar hosil qiladi."},
  {"symbol":"Eu","name":"Yevropiy","category":"lantanoid","state":"qattiq","oxid":[2,3],"ion":"Eu²⁺","reactivity":"o'rta","notes":"EuO hosil qiladi; qaytaruvchi."},
  {"symbol":"Gd","name":"Gadoliniy","category":"lantanoid","state":"qattiq","oxid":[3],"ion":"Gd³⁺","reactivity":"o'rta","notes":"Magnit xususiyatli; oksidlar hosil qiladi."},
  {"symbol":"Tb","name":"Terbiy","category":"lantanoid","state":"qattiq","oxid":[3,4],"ion":"Tb³⁺","reactivity":"o'rta","notes":"Terbiy oksidlarini hosil qiladi."},
  {"symbol":"Dy","name":"Disproziy","category":"lantanoid","state":"qattiq","oxid":[3],"ion":"Dy³⁺","reactivity":"o'rta","notes":"Galogenidlar hosil qiladi."},
  {"symbol":"Ho","name":"Golmiy","category":"lantanoid","state":"qattiq","oxid":[3],"ion":"Ho³⁺","reactivity":"o'rta","notes":"Oksidlar va galogenidlar hosil qiladi."},
  {"symbol":"Er","name":"Erbiy","category":"lantanoid","state":"qattiq","oxid":[3],"ion":"Er³⁺","reactivity":"o'rta","notes":"Oksidlar hosil qiladi."},
  {"symbol":"Tm","name":"Tuliy","category":"lantanoid","state":"qattiq","oxid":[3],"ion":"Tm³⁺","reactivity":"o'rta","notes":"Galogenidlar hosil qiladi."},
  {"symbol":"Yb","name":"Itterbiy","category":"lantanoid","state":"qattiq","oxid":[2,3],"ion":"Yb²⁺","reactivity":"o'rta","notes":"Reaktiv lantanoid metall."},
  {"symbol":"Lu","name":"Lyutetsiy","category":"lantanoid","state":"qattiq","oxid":[3],"ion":"Lu³⁺","reactivity":"past","notes":"Eng barqaror lantanoid."},
  {"symbol":"Hf","name":"Gafniy","category":"o'tish metalli","state":"qattiq","oxid":[4],"ion":null,"reactivity":"past","notes":"Chidamli metall."},
  {"symbol":"Ta","name":"Tantal","category":"o'tish metalli","state":"qattiq","oxid":[5],"ion":null,"reactivity":"juda past","notes":"Juda inert."},
  {"symbol":"W","name":"Volfram","category":"o'tish metalli","state":"qattiq","oxid":[4,6],"ion":null,"reactivity":"o'rta","notes":"WO₃ hosil qiladi."},
  {"symbol":"Re","name":"Reniy","category":"o'tish metalli","state":"qattiq","oxid":[4,7],"ion":null,"reactivity":"past","notes":"Noyob metall."},
  {"symbol":"Os","name":"Osmiy","category":"o'tish metalli","state":"qattiq","oxid":[4,8],"ion":null,"reactivity":"o'rta","notes":"Osmiy tetroksid hosil qiladi."},
  {"symbol":"Ir","name":"Iridiy","category":"o'tish metalli","state":"qattiq","oxid":[3,4],"ion":null,"reactivity":"juda past","notes":"Yuqori darajada inert."},
  {"symbol":"Pt","name":"Platina","category":"o'tish metalli","state":"qattiq","oxid":[2,4],"ion":null,"reactivity":"juda past","notes":"Katalizator; inert."},
  {"symbol":"Au","name":"Oltin","category":"o'tish metalli","state":"qattiq","oxid":[1,3],"ion":"Au³⁺","reactivity":"juda past","notes":"Yuqori darajada inert; AuCl₃ hosil qiladi."},
  {"symbol":"Hg","name":"Simob","category":"metall","state":"suyuq","oxid":[1,2],"ion":"Hg²⁺","reactivity":"o'rta","notes":"Amalgamalar hosil qiladi; oltingugurt bilan reaksiyaga kirishadi."},
  {"symbol":"Tl","name":"Talliy","category":"metall","state":"qattiq","oxid":[1,3],"ion":"Tl⁺","reactivity":"o'rta","notes":"Tl₂O₃ hosil qiladi."},
  {"symbol":"Pb","name":"Qo'rg'oshin","category":"metall","state":"qattiq","oxid":[2,4],"ion":"Pb²⁺","reactivity":"o'rta","notes":"PbO, PbS cho'kmasini hosil qiladi."},
  {"symbol":"Bi","name":"Vismut","category":"metall","state":"qattiq","oxid":[3,5],"ion":"Bi³⁺","reactivity":"o'rta","notes":"BiOCl, Bi₂O₃ hosil qiladi."},
  {"symbol":"Po","name":"Poloniy","category":"metall","state":"qattiq","oxid":[2,4],"ion":null,"reactivity":"o'rta","notes":"Radioaktiv."},
  {"symbol":"At","name":"Astat","category":"galogensimon","state":"qattiq","oxid":[-1,1,3,5,7],"ion":"At⁻","reactivity":"past","notes":"Juda kamyob."},
  {"symbol":"Rn","name":"Radon","category":"asil gaz","state":"gaz","oxid":[2],"ion":null,"reactivity":"juda past","notes":"Radioaktiv asil gaz."},
  {"symbol":"Fr","name":"Fransiy","category":"ishqoriy metall","state":"qattiq","oxid":[1],"ion":"Fr⁺","reactivity":"juda yuqori","notes":"Yuqori reaktivlik; beqaror."},
  {"symbol":"Ra","name":"Radiy","category":"ishqoriy yer metall","state":"qattiq","oxid":[2],"ion":"Ra²⁺","reactivity":"yuqori","notes":"RaSO₄ hosil qiladi; radioaktiv."},
  {"symbol":"Ac","name":"Aktiniy","category":"aktinoid","state":"qattiq","oxid":[3],"ion":"Ac³⁺","reactivity":"o'rta","notes":"AcCl₃ hosil qiladi."},
  {"symbol":"Th","name":"Toriy","category":"aktinoid","state":"qattiq","oxid":[4],"ion":"Th⁴⁺","reactivity":"o'rta","notes":"Toriy dioksid hosil qiladi."},
  {"symbol":"Pa","name":"Protaktiniy","category":"aktinoid","state":"qattiq","oxid":[5],"ion":null,"reactivity":"o'rta","notes":"Radioaktiv; oksidlar hosil qiladi."},
  {"symbol":"U","name":"Uran","category":"aktinoid","state":"qattiq","oxid":[4,6],"ion":null,"reactivity":"o'rta","notes":"UO₂, UO₃ hosil qiladi."},
  {"symbol":"Np","name":"Neptuniy","category":"aktinoid","state":"qattiq","oxid":[3,4,5,6],"ion":null,"reactivity":"o'rta","notes":"Ko'plab oksidlar hosil qiladi."},
  {"symbol":"Pu","name":"Plutoniy","category":"aktinoid","state":"qattiq","oxid":[3,4,5,6],"ion":null,"reactivity":"o'rta","notes":"PuO₂ hosil qiladi."},
  {"symbol":"Am","name":"Ameritsiy","category":"aktinoid","state":"qattiq","oxid":[3],"ion":"Am³⁺","reactivity":"o'rta","notes":"AmO₂ hosil qiladi."},
  {"symbol":"Cm","name":"Kyuriy","category":"aktinoid","state":"qattiq","oxid":[3],"ion":"Cm³⁺","reactivity":"o'rta","notes":"Halogenidlar hosil qiladi."},
  {"symbol":"Bk","name":"Berkliy","category":"aktinoid","state":"qattiq","oxid":[3,4],"ion":null,"reactivity":"o'rta","notes":"Noyob."},
  {"symbol":"Cf","name":"Kaliforniy","category":"aktinoid","state":"qattiq","oxid":[3],"ion":"Cf³⁺","reactivity":"o'rta","notes":"Radioaktiv."},
  {"symbol":"Es","name":"Eynshteyniy","category":"aktinoid","state":"qattiq","oxid":[3],"ion":null,"reactivity":"o'rta","notes":"Oksidlar hosil qiladi."},
  {"symbol":"Fm","name":"Fermiy","category":"aktinoid","state":"qattiq","oxid":[3],"ion":null,"reactivity":"o'rta","notes":"Noyob; beqaror."},
  {"symbol":"Md","name":"Mendeleviy","category":"aktinoid","state":"qattiq","oxid":[3],"ion":"Md³⁺","reactivity":"o'rta","notes":"Radioaktiv."},
  {"symbol":"No","name":"Nobeliy","category":"aktinoid","state":"qattiq","oxid":[2,3],"ion":"No²⁺","reactivity":"o'rta","notes":"Noyob."},
  {"symbol":"Lr","name":"Lourensiy","category":"aktinoid","state":"qattiq","oxid":[3],"ion":"Lr³⁺","reactivity":"o'rta","notes":"Juda noyob."},
  {"symbol":"Rf","name":"Rezerfordiy","category":"sintetik metall","state":"qattiq","oxid":[4],"ion":null,"reactivity":"noma'lum","notes":"Qisqa yarim yemirilish davri."},
  {"symbol":"Db","name":"Dubniy","category":"sintetik metall","state":"qattiq","oxid":[5],"ion":null,"reactivity":"noma'lum","notes":"Qisqa yarim yemirilish davri."},
  {"symbol":"Sg","name":"Siborgiy","category":"sintetik metall","state":"qattiq","oxid":[6],"ion":null,"reactivity":"noma'lum","notes":"Qisqa yarim yemirilish davri."},
  {"symbol":"Bh","name":"Boriy","category":"sintetik metall","state":"qattiq","oxid":[7],"ion":null,"reactivity":"noma'lum","notes":"Juda noyob."},
  {"symbol":"Hs","name":"Xassiy","category":"sintetik metall","state":"qattiq","oxid":[8],"ion":null,"reactivity":"noma'lum","notes":"Juda noyob."},
  {"symbol":"Mt","name":"Meytneriy","category":"sintetik metall","state":"qattiq","oxid":[],"ion":null,"reactivity":"noma'lum","notes":"Juda noyob."},
  {"symbol":"Ds","name":"Darmshtadtiy","category":"sintetik metall","state":"qattiq","oxid":[],"ion":null,"reactivity":"noma'lum","notes":"Juda noyob."},
  {"symbol":"Rg","name":"Rentgeniy","category":"sintetik metall","state":"qattiq","oxid":[1],"ion":"Rg⁺","reactivity":"noma'lum","notes":"Oltinga o'xshash bo'lishi kutilmoqda."},
  {"symbol":"Cn","name":"Kopernitsiy","category":"sintetik metall","state":"suyuq","oxid":[2],"ion":null,"reactivity":"noma'lum","notes":"Simobsimon."},
  {"symbol":"Nh","name":"Nixoniy","category":"sintetik metall","state":"qattiq","oxid":[1],"ion":null,"reactivity":"noma'lum","notes":"Juda beqaror."},
  {"symbol":"Fl","name":"Fleroviy","category":"sintetik metall","state":"qattiq","oxid":[2,4],"ion":null,"reactivity":"noma'lum","notes":"Metall/yarimmetall ekanligi bahsli."},
  {"symbol":"Mc","name":"Moskoviy","category":"sintetik metall","state":"qattiq","oxid":[1,3],"ion":null,"reactivity":"noma'lum","notes":"Juda beqaror."},
  {"symbol":"Lv","name":"Livermoriy","category":"sintetik metall","state":"qattiq","oxid":[2],"ion":null,"reactivity":"noma'lum","notes":"Juda beqaror."},
  {"symbol":"Ts","name":"Tennessin","category":"galogensimon","state":"qattiq","oxid":[-1,1,3,5,7],"ion":"Ts⁻","reactivity":"noma'lum","notes":"Og'ir galogenga o'xshaydi."},
  {"symbol":"Og","name":"Oganesson","category":"asil gazsimon","state":"gaz","oxid":[2],"ion":null,"reactivity":"noma'lum","notes":"Juda beqaror og'ir asil gaz."}
];
// 1. Ranglar
export const COLORS = {
  primary: '#0068FF',
  secondary: '#00C2A8',
  accent: '#FF9F43',
  background: '#F7FAFF',
  surface: '#FFFFFF',
  success: '#2DD4BF',
  error: '#FF5A5F',
  text: '#0F172A',
  muted: '#475569',
  white: '#FFFFFF'
};

// 2. YUTUQLAR RO'YXATI (Yangilandi)
export const ACHIEVEMENTS_LIST = [
  { 
    id: 'first_discovery', 
    title: 'Birinchi qadam',  // Rasmga moslandi
    description: 'Ilk bor laboratoriya topshirig\'ini bajardingiz!', 
    icon: '🚀' 
  },
  { 
    id: 'quiz_master', 
    title: 'Zukko',  // Rasmga moslandi
    description: 'Topshiriqda 100% natija ko\'rsatdingiz.', 
    icon: '🎯' 
  },
  { 
    id: 'streak_3', 
    title: 'Barqaror', 
    description: '3 kun ketma-ket mashg\'ulot qildingiz.', 
    icon: '🔥' 
  },
  { 
    id: 'science_nerd', 
    title: 'Fanat', 
    description: 'Bitta fandan barcha darslarni ko\'rib chiqdingiz.', 
    icon: '🤓' 
  },
  { 
    id: 'speed_runner', 
    title: 'Tezkor', 
    description: 'Topshiriqni 1 daqiqadan kam vaqtda bajardingiz.', 
    icon: '⚡' 
  },
  { 
    id: 'level_5', 
    title: 'Professional', 
    description: '5-darajaga (Level 5) yetdingiz.', 
    icon: '🏆' 
  }
];
// VIDEO LINKLAR (15 soniyalik tezkor videolar)
const VID_1 = "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4";
const VID_2 = "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4";
const VID_3 = "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4";
const VID_4 = "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4";
const VID_5 = "https://storage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4";



// 3. KURSLAR VA DARSLAR RO'YXATI
export const COURSES: Course[] = [
  {
    id: SubjectType.CHEMISTRY,
    title: 'Kimyo',
    description: 'Moddalar, elementlar va reaksiyalar.',
    color: COLORS.primary,
    icon: 'Atom',
    lessons: [
      {
        id: 'chem-1',
        title: '1. Kislota va Asoslar',
        description: 'pH balansi va neytrallash jarayoni.',
        videoUrl: VID_1, // 15 sek
        thumbnail: 'https://picsum.photos/400/225?random=1',
        duration: '15 soniya',
        taskConfig: {
          type: SubjectType.CHEMISTRY,
          instructions: 'Eritmani neytrallang! Kislotaga asos qo\'shib, pH darajasini 7.0 ga keltiring.',
          targetValue: 7.0,
          tolerance: 0.5,
          initialParams: { ph: 2.0, volume: 50 },
        },
      },
      {
        id: 'chem-2',
        title: '2. Kovalent Bog\'lanish',
        description: 'Atomlar elektronlarni qanday bo\'lishadi?',
        videoUrl: VID_2, // 15 sek
        thumbnail: 'https://picsum.photos/400/225?random=2',
        duration: '15 soniya',
        taskConfig: {
          type: SubjectType.CHEMISTRY,
          instructions: 'Barqaror molekula hosil qilish uchun elektronlar sonini to\'g\'rilang (Oktet qoidasi).',
          targetValue: 8,
          tolerance: 0,
          initialParams: { electrons: 4, volume: 0 },
        },
      },
      {
        id: 'chem-3',
        title: '3. Davriy Jadval',
        description: 'Elementlarning xossalari va joylashuvi.',
        videoUrl: VID_3, // 15 sek
        thumbnail: 'https://picsum.photos/400/225?random=3',
        duration: '15 soniya',
        taskConfig: {
          type: SubjectType.CHEMISTRY,
          instructions: 'Ideal gaz holati uchun temperaturani Selsiyda sozlang (25°C xona harorati).',
          targetValue: 25,
          tolerance: 2,
          initialParams: { temp: 0, pressure: 1 },
        },
      },
      {
        id: 'chem-4',
        title: '4. Kimyoviy Reaksiyalar',
        description: 'Ekzotermik va endotermik jarayonlar.',
        videoUrl: VID_4, // 15 sek
        thumbnail: 'https://picsum.photos/400/225?random=4',
        duration: '15 soniya',
        taskConfig: {
          type: SubjectType.CHEMISTRY,
          instructions: 'Reaksiya tezligini oshirish uchun katalizator miqdorini 50mg ga yetkazing.',
          targetValue: 50,
          tolerance: 5,
          initialParams: { catalyst: 10, heat: 30 },
        },
      },
      {
        id: 'chem-5',
        title: '5. Eritmalar',
        description: 'Konsentratsiya va to\'yinish.',
        videoUrl: VID_5, // Qisqa
        thumbnail: 'https://picsum.photos/400/225?random=5',
        duration: '15 soniya',
        taskConfig: {
          type: SubjectType.CHEMISTRY,
          instructions: 'Eritma konsentratsiyasini 10% ga tushirish uchun suv qo\'shing.',
          targetValue: 10,
          tolerance: 1,
          initialParams: { concentration: 50, water: 0 },
        },
      },
    ],
  },
  {
    id: SubjectType.PHYSICS,
    title: 'Fizika',
    description: 'Kuch, energiya va harakat qonunlari.',
    color: COLORS.accent,
    icon: 'Zap',
    lessons: [
      {
        id: 'phys-1',
        title: '1. Om Qonuni',
        description: 'Kuchlanish, Tok va Qarshilik.',
        videoUrl: VID_2,
        thumbnail: 'https://picsum.photos/400/225?random=6',
        duration: '15 soniya',
        taskConfig: {
          type: SubjectType.PHYSICS,
          instructions: 'Tok kuchi (I) roppa-rosa 2.0 Amper bo\'lishi uchun Kuchlanishni (V) sozlang (R=5 Om).',
          targetValue: 2.0,
          tolerance: 0.1,
          initialParams: { voltage: 5, resistance: 5 },
        },
      },
      {
        id: 'phys-2',
        title: '2. Nyuton Qonunlari',
        description: 'Kuch va harakat.',
        videoUrl: VID_3,
        thumbnail: 'https://picsum.photos/400/225?random=7',
        duration: '15 soniya',
        taskConfig: {
          type: SubjectType.PHYSICS,
          instructions: 'Jism tezlanishi 5 m/s² bo\'lishi uchun unga ta\'sir qiluvchi kuchni toping (m=10kg).',
          targetValue: 50,
          tolerance: 2,
          initialParams: { force: 0, mass: 10 },
        },
      },
      {
        id: 'phys-3',
        title: '3. Gravitatsiya',
        description: 'Erkin tushish tezlanishi.',
        videoUrl: VID_4,
        thumbnail: 'https://picsum.photos/400/225?random=8',
        duration: '15 soniya',
        taskConfig: {
          type: SubjectType.PHYSICS,
          instructions: 'Raketa uchishi uchun tortish kuchini (G) yengib o\'tadigan kuchlanishni 100% ga yetkazing.',
          targetValue: 100,
          tolerance: 1,
          initialParams: { thrust: 0, gravity: 9.8 },
        },
      },
      {
        id: 'phys-4',
        title: '4. Optika',
        description: 'Yorug\'likning sinishi va qaytishi.',
        videoUrl: VID_1,
        thumbnail: 'https://picsum.photos/400/225?random=9',
        duration: '15 soniya',
        taskConfig: {
          type: SubjectType.PHYSICS,
          instructions: 'Yorug\'likni to\'liq qaytarish uchun tushish burchagini 45 gradusga sozlang.',
          targetValue: 45,
          tolerance: 2,
          initialParams: { angle: 0, refraction: 1.5 },
        },
      },
      {
        id: 'phys-5',
        title: '5. Termodinamika',
        description: 'Issiqlik uzatish usullari.',
        videoUrl: VID_5,
        thumbnail: 'https://picsum.photos/400/225?random=10',
        duration: '15 soniya',
        taskConfig: {
          type: SubjectType.PHYSICS,
          instructions: 'Tizim muvozanatga kelishi uchun temperaturani 50°C ga tushiring.',
          targetValue: 50,
          tolerance: 5,
          initialParams: { temp: 100, energy: 500 },
        },
      },
    ],
  },
  {
    id: SubjectType.BIOLOGY,
    title: 'Biologiya',
    description: 'Hayot, hujayralar va ekotizim.',
    color: COLORS.secondary,
    icon: 'Sprout',
    lessons: [
      {
        id: 'bio-1',
        title: '1. Fotosintez',
        description: 'Yorug\'lik energiyasi va o\'simliklar.',
        videoUrl: VID_3,
        thumbnail: 'https://picsum.photos/400/225?random=11',
        duration: '15 soniya',
        taskConfig: {
          type: SubjectType.BIOLOGY,
          instructions: 'O\'simlik o\'sishi 100% bo\'lishi uchun Yorug\'lik va CO2 miqdorini optimallashtiring.',
          targetValue: 100,
          tolerance: 5,
          initialParams: { light: 20, co2: 20 },
        },
      },
      {
        id: 'bio-2',
        title: '2. Hujayra Tuzilishi',
        description: 'Membrana, yadro va mitoxondriya.',
        videoUrl: VID_1,
        thumbnail: 'https://picsum.photos/400/225?random=12',
        duration: '15 soniya',
        taskConfig: {
          type: SubjectType.BIOLOGY,
          instructions: 'Hujayra energiyasini (ATP) oshirish uchun mitoxondriya faolligini 80% ga ko\'taring.',
          targetValue: 80,
          tolerance: 5,
          initialParams: { activity: 20, glucose: 50 },
        },
      },
      {
        id: 'bio-3',
        title: '3. DNK va Genetika',
        description: 'Irsiyat qonunlari.',
        videoUrl: VID_4,
        thumbnail: 'https://picsum.photos/400/225?random=13',
        duration: '15 soniya',
        taskConfig: {
          type: SubjectType.BIOLOGY,
          instructions: 'DNK zanjirini barqarorlashtirish uchun haroratni 37°C (tana harorati) ga sozlang.',
          targetValue: 37,
          tolerance: 0.5,
          initialParams: { temp: 20, stability: 0 },
        },
      },
      {
        id: 'bio-4',
        title: '4. Ekotizimlar',
        description: 'Oziq zanjiri va muvozanat.',
        videoUrl: VID_2,
        thumbnail: 'https://picsum.photos/400/225?random=14',
        duration: '15 soniya',
        taskConfig: {
          type: SubjectType.BIOLOGY,
          instructions: 'Ekotizim balansi uchun yirtqichlar va o\'lja nisbatini 1:10 ga keltiring (10 yirtqich).',
          targetValue: 10,
          tolerance: 1,
          initialParams: { predators: 2, prey: 100 },
        },
      },
      {
        id: 'bio-5',
        title: '5. Inson Anatomiyasi',
        description: 'Yurak va qon aylanish tizimi.',
        videoUrl: VID_5,
        thumbnail: 'https://picsum.photos/400/225?random=15',
        duration: '15 soniya',
        taskConfig: {
          type: SubjectType.BIOLOGY,
          instructions: 'Yurak urish tezligini (Puls) normal holatga, ya\'ni 70 zarba/daqiqaga tushiring.',
          targetValue: 70,
          tolerance: 5,
          initialParams: { bpm: 120, adrenaline: 50 },
        },
      },
    ],
  },
];